name: ci-golang-workflow
on: 
  pull_request:
    branches:
      - develop

jobs: 
  check-application:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        go: ['1.14', '1.15', '1.16', '1.17', '1.18']
    steps:
     - uses: actions/checkout@v4
     - uses: actions/setup-go@v5
       with:
         go-version: ${{matrix.go}}
     - run: go test
     - run: go run sum.go